FROM alpine
ENV TZ=Europe/Kiev
RUN apt-get update 
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install apache2 -y 
EXPOSE 80
cmd ["apache2ctl", "-D", "FOREGROUND"]
